sdk/client: the `Content-Length` header should be set for DELETE/PATCH requests
hashicorp/go-azure-sdk pull request #448
Opened 2023-05-04 07:07 UTC by tombuildsstuff

and match the size of the payload

2023-05-04 07:13 UTC, jackofallops approved these changes
LGTM 👍

2023-05-04 08:21 UTC, tombuildsstuff commented on sdk/client/client.go
> +		req.Header.Set("Content-Length", fmt.Sprintf("%d", contentLength))
looks like this header is being stripped out when it's explicitly set to a `0` value, setting this (and the original logic) fails when it's set to `0`, but this works fine if another header is used

2023-05-09 12:38 UTC, manicminer commented
It seems like the stripping of the `Content-Length` and `Transfer-Encoding` headers is due to https://github.com/hashicorp/go-retryablehttp/pull/194 - neither of these headers need to be (or should be) manually set in the `Header` field, they are determined by `net/http` as part of the transport handling for HTTP/1.1 and HTTP/2.0. Accordingly, I think we should stop trying to set them manually (since it has no effect anyway due to them being automatically replaced by `net/http`) and wait for https://github.com/hashicorp/go-retryablehttp/pull/194.

2023-05-09 12:39 UTC, manicminer requested changes
It seems like the stripping of the `Content-Length` and `Transfer-Encoding` headers is due to https://github.com/hashicorp/go-retryablehttp/pull/194 - neither of these headers need to be (or should be) manually set in the `Header` field, they are determined by `net/http` as part of the transport handling for HTTP/1.1 and HTTP/2.0. Accordingly, I think we should stop trying to set them manually (since it has no effect anyway due to them being automatically replaced by `net/http`) and wait for https://github.com/hashicorp/go-retryablehttp/pull/194.

2023-06-06 18:23 UTC, closed without merging