Bugfix: handle errors where the `details` field is returned as an object instead of an array of objects
hashicorp/go-azure-sdk pull request #501
Opened 2023-06-06 21:30 UTC by manicminer

2023-06-06 21:37 UTC, mbfrahry approved these changes
LGTM!

2023-06-07 07:24 UTC, tombuildsstuff requested changes

2023-06-07 13:33 UTC, manicminer commented on sdk/odata/errors.go
> +	}
Sure thing 👍

2023-07-04 10:56 UTC, tombuildsstuff commented on sdk/odata/errors.go
> +	}
Rebased this / pushed a commit to conditionally try deserialising this into both types without parsing the response fwiw

2023-07-04 10:57 UTC, tombuildsstuff approved these changes

2023-07-04 18:03 UTC, manicminer commented on sdk/odata/errors.go
> +	}
Looks good, thanks for that 👍

2023-07-04 18:04 UTC, merged